server {
    listen 80;

    server_name phpapipro.dev.localhost;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    http2 on;

    server_name phpapipro.dev.localhost;

    root /phpapipro/public;

    index index.php index.html index.htm;

    ssl_certificate /etc/nginx/certs/phpapipro.dev.localhost+3.pem;
    ssl_certificate_key /etc/nginx/certs/phpapipro.dev.localhost+3-key.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers HIGH:!aNULL:!MD5;

    access_log /dev/stdout;
    error_log /dev/stderr warn; # Nível 'warn' é mais apropriado para dev do que 'debug'

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass php:9000;

        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }
}