CREATE DATABASE IF NOT EXISTS api_pro CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE api_pro;

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(160) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT = 'user',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);